# Config Back
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontback
    tier: back
  name: back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontback
      tier: back
  template:
    metadata:
      labels:
        app: frontback
        tier: back
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_NAME
          value: news
        - name: DATABASE_PASSWORD
          value: postgres
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PORT
          value: "5432"
        image: komarovma/devops-netology:backend
        imagePullPolicy: "IfNotPresent"
        name: back
        ports:
        - containerPort: 8080
      restartPolicy: Always
# Config Service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontback
    tier: back
  name: back
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: frontback
    tier: back