apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontback
  name: frontback
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontback
  template:
    metadata:
      labels:
        app: frontback
    spec:
      containers:
      - image: komarovma/devops-netology:frontend
        imagePullPolicy: IfNotPresent
        volumeMounts:
            - mountPath: /data/front
              name: postgredb
        name: frontend
      - image: komarovma/devops-netology:backend
        imagePullPolicy: IfNotPresent
        volumeMounts:
            - mountPath: /data/back
              name: postgredb
        name: backend
        env:
          - name: HTTP_PORT
            value: "8080"
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim